### ISSUE TITLE
lpa() should not take delta as a parameter

### ISSUE THREAD

**Issue by kawadia** [kawadia/estrangement#15]
lpa should not need delta.
Its only used for logging which can be removed.

maxQ should also not take delta as a parameter.

**Comment by dabideen** [comment]
I added it back to maxQ because it is needed by best_partition which is called from inside maxQ

**Comment by kawadia** [comment]
maxQ should still not take delta as a parameter. You can pass in delta=1 to
best_partition when it is called from inside maxQ. delta does not matter
anyway when lambuh=0

On Tue, Jul 10, 2012 at 2:09 PM, dabideen <
reply@reply.github.com

**Comment by dabideen** [comment]
I see. I removed it again.
