### ISSUE TITLE
Cleanup plotting code

### ISSUE THREAD

**Issue by kawadia** [kawadia/estrangement#2]
Remove unnecessary functions and duplication between plot_labels and postpro.py

**Comment by dabideen** [comment]
Installation was a pain because of the number of dependencies, that were not all easy to get....a lot related to graphing, if we minimize the graphing functions to the basic essentials it would be simpler and neater. maybe?

**Comment by kawadia** [comment]
Just deleted some 3d plotting code using mayavi2. Thats a major dependency and actually I was not even calling the function in the final code.

**Comment by dabideen** [comment]
I think this is done. Will mark any more I notice.
